import { nanoid } from "@reduxjs/toolkit";

export const cards = [
  {
    id: nanoid(),
    name: "angular2",
    img: "https://backendless.com/wp-content/uploads/2016/04/angular2.png",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "vue",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Vue.js_Logo_2.svg/1200px-Vue.js_Logo_2.svg.png",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "react",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/1200px-React-icon.svg.png",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "grunt",
    img: "https://gruntjs.com/img/og.png",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "phantomjs",
    img: "https://tech.buzzvil.com/wp-content/uploads/2014/05/Scaling-PhantomJS-With-Ghost-Town.jpg",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "ember",
    img: "https://upload.wikimedia.org/wikipedia/en/6/69/Ember.js_Logo_and_Mascot.png",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "babel",
    img: "https://ih1.redbubble.net/image.370345718.1971/poster,504x498,f8f8f8-pad,600x600,f8f8f8.u1.jpg",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "ionic",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQG9p6YJL9D1MGSb49E14EPX2unp50_KLBqHUwdnYGwy5B72Y8a8P4daamTKs30Man3UsA&usqp=CAU",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "glup",
    img: "https://images.g2crowd.com/uploads/product/image/large_detail/large_detail_138998112a94210ed276d174d27293f8/gulpjs.png",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "meteor",
    img: "https://v6i7z7i8.rocketcdn.me/wp-content/uploads/2016/04/meteor-1.png",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "yeoman",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8xr8G8Vpxat-5T5u1UcWYw8huAj1B5htsYLX2-KEdytWApsQTwOZEFXYGVWhmENMKiH8&usqp=CAU",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "yarn",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmfxuQNsNG-WTSyYpPS87Hm-YpiHx5_NJBXp60P-KCfQM1c-lPQavnjHKwWO_2wL4Roso&usqp=CAU",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "nodejs",
    img: "https://www.devteam.space/wp-content/uploads/2022/05/nodejs.jpg",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "bower",
    img: "https://bower.io/img/bower-logo.png",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "browserify",
    img: "https://upload.wikimedia.org/wikipedia/en/thumb/2/27/Browserify.svg/800px-Browserify.svg.png",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "angular2",
    img: "https://backendless.com/wp-content/uploads/2016/04/angular2.png",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "vue",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Vue.js_Logo_2.svg/1200px-Vue.js_Logo_2.svg.png",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "react",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/React-icon.svg/1200px-React-icon.svg.png",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "grunt",
    img: "https://gruntjs.com/img/og.png",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "phantomjs",
    img: "https://tech.buzzvil.com/wp-content/uploads/2014/05/Scaling-PhantomJS-With-Ghost-Town.jpg",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "ember",
    img: "https://upload.wikimedia.org/wikipedia/en/6/69/Ember.js_Logo_and_Mascot.png",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "babel",
    img: "https://ih1.redbubble.net/image.370345718.1971/poster,504x498,f8f8f8-pad,600x600,f8f8f8.u1.jpg",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "ionic",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQG9p6YJL9D1MGSb49E14EPX2unp50_KLBqHUwdnYGwy5B72Y8a8P4daamTKs30Man3UsA&usqp=CAU",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "glup",
    img: "https://images.g2crowd.com/uploads/product/image/large_detail/large_detail_138998112a94210ed276d174d27293f8/gulpjs.png",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "meteor",
    img: "https://v6i7z7i8.rocketcdn.me/wp-content/uploads/2016/04/meteor-1.png",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "yeoman",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR8xr8G8Vpxat-5T5u1UcWYw8huAj1B5htsYLX2-KEdytWApsQTwOZEFXYGVWhmENMKiH8&usqp=CAU",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "yarn",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmfxuQNsNG-WTSyYpPS87Hm-YpiHx5_NJBXp60P-KCfQM1c-lPQavnjHKwWO_2wL4Roso&usqp=CAU",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "nodejs",
    img: "https://www.devteam.space/wp-content/uploads/2022/05/nodejs.jpg",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "bower",
    img: "https://bower.io/img/bower-logo.png",
    IsItTurned: false,
  },
  {
    id: nanoid(),
    name: "browserify",
    img: "https://upload.wikimedia.org/wikipedia/en/thumb/2/27/Browserify.svg/800px-Browserify.svg.png",
    IsItTurned: false,
  },
];
